server:
  port : 8000
spring:
  devtools:
    Livereload:
      enabled : true
  datasource:
    url : jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password : 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
mybatis:
  config-location: classpath:config/myBatis.xml


jwt:
  secret_key: acoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacooacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoacoaco
  expTime: 86400000

file: E:\insta\insta\src\main\resources\static